### ISSUE TITLE
build error in linux, please check it.

### ISSUE THREAD

**Issue by mimijava** [csuft/VideoTimeline#1]
In file included from ../Qt5.11.0/5.11.0/gcc_64/include/QtCore/qglobal.h:1194:0,
                 from ../Qt5.11.0/5.11.0/gcc_64/include/QtGui/qtguiglobal.h:43,
                 from ../Qt5.11.0/5.11.0/gcc_64/include/QtWidgets/qtwidgetsglobal.h:43,
                 from ../Qt5.11.0/5.11.0/gcc_64/include/QtWidgets/qapplication.h:43,
                 from ../Qt5.11.0/5.11.0/gcc_64/include/QtWidgets/QApplication:1,
                 from ../untitled/main.cpp:1:
../Qt5.11.0/5.11.0/gcc_64/include/QtCore/qtypeinfo.h:246:7: error: specialization of ?template<class T> class QTypeInfo? in different namespace [-fpermissive]
 class QTypeInfo<TYPE > \
       ^
../Qt5.11.0/5.11.0/gcc_64/include/QtCore/qtypeinfo.h:265:1: note: in expansion of macro ?Q_DECLARE_TYPEINFO_BODY?
 Q_DECLARE_TYPEINFO_BODY(TYPE, FLAGS)
 ^
../untitled/timelinetrackmodel.h:50:2: note: in expansion of macro ?Q_DECLARE_TYPEINFO?
  Q_DECLARE_TYPEINFO(ClipInfo, Q_COMPLEX_TYPE);
  ^
../Qt5.11.0/5.11.0/gcc_64/include/QtCore/qtypeinfo.h:57:7: error:   from definition of ?template<class T> class QTypeInfo? [-fpermissive]
 class QTypeInfo
       ^
../untitled/timelinetrackmodel.h:50:21: error: ?ClipInfo? was not declared in this scope
  Q_DECLARE_TYPEINFO(ClipInfo, Q_COMPLEX_TYPE);

**Comment by peppemas** [comment]
same problem... did you solve it ?
